import type { Metadata } from "next";
import {Poppins } from "next/font/google";
import "./globals.css";
import ChatProvider from "@/provider/ChatProvider";

const inter =Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ChatProvider>{children}</ChatProvider>
      </body>
    </html>
  );
}
